apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./knative/serving
  prune: true
  validation: client